#ifndef WARZONEGAME2_CARDS_FWD_H
#define WARZONEGAME2_CARDS_FWD_H
class Card;
class Reinforcement;
class Blockade;
class Airlift;
class Diplomacy;
class Hand;
class Deck;
#endif //WARZONEGAME2_ORDERS_FWD_H